version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Docker/php-app.dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html:delegated
      - ./app/vendor:/var/www/html/vendor:delegated
      - ./app/storage:/var/www/html/storage:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - mysql
    command: >
      bash -c "php artisan migrate && php-fpm"

  composer:
    image: composer:latest
    container_name: laravel-composer
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html:delegated
    networks:
      - laravel
    command: composer install

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: super_secret_123
      MYSQL_DATABASE: laravel
      MYSQL_USER: user123
      MYSQL_PASSWORD: secret_123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: super_secret_123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel: